## Importing Libraries

In [ ]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix, accuracy_score

## Importing Dataset




In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
dataset = pd.read_csv('feedback-nlp.csv')
dataset.head(1)

Computer Networks (Feedback)  \
0  The sessions were fine, but there was a lack o...   

  Computer Networks (Satisfaction)  \
0                          Neutral   

                         Machine Learning (Feedback)  \
0  It was an average experience overall; the facu...   

  Machine Learning (Satisfaction)  \
0                         Neutral   

                         Operating System (Feedback)  \
0  The faculty did not engage the class effective...   

  Operating System (Satisfaction)  \
0                        Negative   

     Computer Organization & Architecture (Feedback)  \
0  The teaching style was acceptable, but the cou...   

  Computer Organization & Architecture (Satisfaction)  
0                                            Neutral

In [ ]:
dataset.shape

(2000, 8)

In [ ]:
df0 = dataset[['Computer Networks (Feedback)', 'Computer Networks (Satisfaction)']]
df1 = dataset[['Machine Learning (Feedback)', 'Machine Learning (Satisfaction)']]
df2 = dataset[['Operating System (Feedback)', 'Operating System (Satisfaction)']]
df3 = dataset[['Computer Organization & Architecture (Feedback)', 'Computer Organization & Architecture (Satisfaction)']]

In [ ]:
# Encoding Categorical Target: Computer Networks (Satisfaction)
from sklearn.preprocessing import LabelEncoder
le0 = LabelEncoder()
le1 = LabelEncoder()
le2 = LabelEncoder()
le3 = LabelEncoder()

df0['Computer Networks (Satisfaction)'] = le0.fit_transform(df0['Computer Networks (Satisfaction)'])
df1['Machine Learning (Satisfaction)'] = le1.fit_transform(df1['Machine Learning (Satisfaction)'])
df2['Operating System (Satisfaction)'] = le2.fit_transform(df2['Operating System (Satisfaction)'])
df3['Computer Organization & Architecture (Satisfaction)'] = le3.fit_transform(df3['Computer Organization & Architecture (Satisfaction)'])

<ipython-input-536-fe713886a5da>:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df0['Computer Networks (Satisfaction)'] = le0.fit_transform(df0['Computer Networks (Satisfaction)'])
<ipython-input-536-fe713886a5da>:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Machine Learning (Satisfaction)'] = le1.fit_transform(df1['Machine Learning (Satisfaction)'])
<ipython-input-536-fe713886a5da>:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_

In [ ]:
df0.head()

Computer Networks (Feedback)  \
0  The sessions were fine, but there was a lack o...   
1  The course was very well-structured and the fa...   
2  The faculty did not engage the class effective...   
3  The faculty did not engage the class effective...   
4  The course was decent but could use more examp...   

   Computer Networks (Satisfaction)  
0                                 1  
1                                 2  
2                                 0  
3                                 0  
4                                 1

### Data Preprocessing

In [ ]:
import re # Regular expression import
import nltk

nltk.download('stopwords')
nltk.download('wordnet')

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

all_stopwords = stopwords.words('english') # Storing stop word in all_stopwords
all_stopwords.remove('not')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [ ]:
## Store students data post data cleaning
corpus0=[] # For Computer Networks
corpus1=[] # For Machine Learning
corpus2=[] # For Operating System
corpus3=[] # For Computer Organization & Architecture

# For Computer Networks
for i in range(0, 2000): # Runs row by row to clean every data we have in our dataset
  review0 = re.sub('[^a-zA-Z]', ' ', df0['Computer Networks (Feedback)'][i]) # Dropping all special symbols
  review0 = review0.lower() # Converting to lower case
  review0 = review0.split()
  review0 = [lemmatizer.lemmatize(word) for word in review0 if not word in set(all_stopwords)]
  review0 = ' '.join(review0)
  corpus0.append(review0)

# For Machine Learning
for i in range(0, 2000): # Runs row by row to clean every data we have in our dataset
  review1 = re.sub('[^a-zA-Z]', ' ', df1['Machine Learning (Feedback)'][i]) # Dropping all special symbols
  review1 = review1.lower() # Converting to lower case
  review1 = review1.split()
  review1 = [lemmatizer.lemmatize(word) for word in review1 if not word in set(all_stopwords)]
  review1 = ' '.join(review1)
  corpus1.append(review1)

# For Operating System
for i in range(0, 2000): # Runs row by row to clean every data we have in our dataset
  review2 = re.sub('[^a-zA-Z]', ' ', df2['Operating System (Feedback)'][i]) # Dropping all special symbols
  review2 = review2.lower() # Converting to lower case
  review2 = review2.split()
  review2 = [lemmatizer.lemmatize(word) for word in review2 if not word in set(all_stopwords)]
  review2 = ' '.join(review2)
  corpus2.append(review2)

# For Computer Organization & Architecture
for i in range(0, 2000): # Runs row by row to clean every data we have in our dataset
  review3 = re.sub('[^a-zA-Z]', ' ', df3['Computer Organization & Architecture (Feedback)'][i]) # Dropping all special symbols
  review3 = review3.lower() # Converting to lower case
  review3 = review3.split()
  review3 = [lemmatizer.lemmatize(word) for word in review3 if not word in set(all_stopwords)]
  review3 = ' '.join(review3)
  corpus3.append(review3)

In [ ]:
# corpus

### Data Transformation

In [ ]:
# Convert cleaned data into bag of words
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 75) # We are taking top 'max_features' most frequent tokens and dropping the left overs

In [ ]:
# For Computer Networks
X0 = cv.fit_transform(corpus0).toarray()
y0 = df0.iloc[:, -1].values

# For Machine Learning
X1 = cv.fit_transform(corpus1).toarray()
y1 = df1.iloc[:, -1].values

# For Operating System
X2 = cv.fit_transform(corpus2).toarray()
y2 = df2.iloc[:, -1].values

# For Computer Organization & Architecture
X3 = cv.fit_transform(corpus3).toarray()
y3 = df3.iloc[:, -1].values

In [ ]:
X0.shape

(2000, 75)

In [ ]:
y0.shape

(2000,)

### Splitting Dataset

In [ ]:
from sklearn.model_selection import train_test_split

X_train0, X_test0, y_train0, y_test0 = train_test_split(X0, y0, test_size = 0.3, random_state = 42) # For Computer Networks
X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1, test_size = 0.3, random_state = 42) # For Machine Learning
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, test_size = 0.3, random_state = 42) # For Operating System
X_train3, X_test3, y_train3, y_test3 = train_test_split(X3, y3, test_size = 0.3, random_state = 42) # For Computer Organization & Architecture

### Model Fitting (Naive Bayes)


In [ ]:
from sklearn.naive_bayes import MultinomialNB

# For Computer Networks
classifier0 = MultinomialNB()
classifier0.fit(X_train0, y_train0)

# For Machine Learning
classifier1 = MultinomialNB()
classifier1.fit(X_train1, y_train1)

# For Operating System
classifier2 = MultinomialNB()
classifier2.fit(X_train2, y_train2)

# For Computer Organization & Architecture
classifier3 = MultinomialNB()
classifier3.fit(X_train3, y_train3)

MultinomialNB()

###Model Performance

In [ ]:
from sklearn.metrics import classification_report

# For Computer Networks
print('For Computer Networks\n')
y_pred0 = classifier0.predict(X_test0)
cm0 = confusion_matrix(y_test0, y_pred0)
print('Confusion Matrix:')
print(cm0)
print('----------------------------------------')
print('Accuracy Score: %.2f' % accuracy_score(y_test0, y_pred0))
print("Classification Report:")
print(classification_report(y_test0, y_pred0, target_names=['Negative', 'Neutral', 'Positive']))
print('###############################################################\n')

# For Machine Learning
print('For Machine Learning\n')
y_pred1 = classifier1.predict(X_test1)
cm1 = confusion_matrix(y_test1, y_pred1)
print('Confusion Matrix:')
print(cm1)
print('----------------------------------------')
print('Accuracy Score: %.2f' % accuracy_score(y_test1, y_pred1))
print("Classification Report:")
print(classification_report(y_test0, y_pred0, target_names=['Negative', 'Neutral', 'Positive']))
print('###############################################################\n')

# For Operating System
print('For Operating System\n')
y_pred2 = classifier2.predict(X_test2)
cm2 = confusion_matrix(y_test2, y_pred2)
print('Confusion Matrix:')
print(cm2)
print('----------------------------------------')
print('Accuracy Score: %.2f' % accuracy_score(y_test2, y_pred2))
print("Classification Report:")
print(classification_report(y_test0, y_pred0, target_names=['Negative', 'Neutral', 'Positive']))
print('###############################################################\n')

# For Computer Organization & Architecture
print('For Computer Organization & Architecture\n')
y_pred3 = classifier3.predict(X_test3)
cm3 = confusion_matrix(y_test3, y_pred3)
print('Confusion Matrix:')
print(cm3)
print('----------------------------------------')
print('Accuracy Score: %.2f' % accuracy_score(y_test3, y_pred3))
print("Classification Report:")
print(classification_report(y_test0, y_pred0, target_names=['Negative', 'Neutral', 'Positive']))

For Computer Networks

Confusion Matrix:
[[203   0   0]
 [ 52 165   0]
 [  0   0 180]]
----------------------------------------
Accuracy Score: 0.91
Classification Report:
              precision    recall  f1-score   support

    Negative       0.80      1.00      0.89       203
     Neutral       1.00      0.76      0.86       217
    Positive       1.00      1.00      1.00       180

    accuracy                           0.91       600
   macro avg       0.93      0.92      0.92       600
weighted avg       0.93      0.91      0.91       600

###############################################################

For Machine Learning

Confusion Matrix:
[[171  32   0]
 [ 37 171   0]
 [  0   0 189]]
----------------------------------------
Accuracy Score: 0.89
Classification Report:
              precision    recall  f1-score   support

    Negative       0.80      1.00      0.89       203
     Neutral       1.00      0.76      0.86       217
    Positive       1.00      1.00      1.00     